### ISSUE TITLE
Not connecting via bluetooth

### ISSUE THREAD

**Issue by SilverDogTech** [brendan-w/python-OBD#102]
I tried to connect to the bluetooth device. I set bluetooth device as a serial port and set that port in pyOBD code, When I click connect it just says "connecting..." and doesn't connect.

I have connected, paired and trusted the OBD bluetooth device but pyOBD won't connect.

**Comment by E-genin** [comment]
Hey, 

I'm facing the same problem, did you manage to solve your problem ?

Thanks

**Comment by apecone** [comment]
Hi SilverDogTech and E-genin, please provide your debug logs.  Here's how...

`obd.logger.setLevel(obd.logging.DEBUG)`

If you provide these logs, I'll take a look :)

**Comment by alistair23** [comment]
Closing as the issue appears to be fixed
