### ISSUE TITLE
obd.OBD() requires explicit path for Bluetooth connection

### ISSUE THREAD

**Issue by E-genin** [brendan-w/python-OBD#105]
Hi there, 
I'm trying to use obd library to connect an ELM327 Bluetooth to a car, I use the very basic script : 

`import obd`
`connection = obd.OBD() # auto-connects to USB or RF port`
`cmd = obd.commands.SPEED # select an OBD command (sensor)`
`response = connection.query(cmd) # send the command, and parse the response`
`print(response.value) # returns unit-bearing values thanks to Pint`
`print(response.value.to("mph")) # user-friendly unit conversions`

The script freezes at this line : 
`connection = obd.OBD() # auto-connects to USB or RF port`
it seems that it enters in an infinite loop and won't get out from there.

Can you help me with this problem.

Thanks in advance.

**Comment by graycrofford** [comment]
Mine takes a good 15-20 seconds with some query items before returning a value. Looks like it is frozen but it isn't.

**Comment by E-genin** [comment]
Hi, Thank you so much for the reply !!

Does the exact same script I mentioned before work for you ?

**Comment by graycrofford** [comment]
I just have a while loop around the response and print lines.

**Comment by E-genin** [comment]
Can you tell the Environment you are developing in (OS, Python version ...)

Thanks

**Comment by alistair23** [comment]
Did you figure out what is going on here?

**Comment by alistair23** [comment]
Is your serial port a standard /dev/ttyS* port?

**Comment by E-genin** [comment]
I think it was a /dev/rfcomm port

**Comment by E-genin** [comment]
After pairing with the dongle, does one have to do something specific before running the script ? 
Because in my case, I didn't have any results until I "linked" the OBD dongle to the /dev/rfcomm in Linux, or to a COM port in Windows.

**Comment by alistair23** [comment]
What do you mean linked?

**Comment by E-genin** [comment]
I meant binding the rfcomm to the dongle's MAC address

**Comment by apecone** [comment]
Hi @E-genin 

Can you please provide your debug logs?  Here's how...

`obd.logger.setLevel(obd.logging.DEBUG)`

If you provide these logs, I'll take a look :)

**Comment by E-genin** [comment]
For that, I'll need a new OBD dongle (I lost the one I had). Once that done, I'll make another test. 
I still remember that it freezes somewhere between the two debugging lines : 
`[obd.obd] Available ports: []`
and the next debugging line.
