### ISSUE TITLE
from .async import Async               ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by fredriccliver** [brendan-w/python-OBD#114]
$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import obd
  File "/usr/local/lib/python3.7/site-packages/obd/__init__.py", line 42
    from .async import Async
              ^
SyntaxError: invalid syntax

Is this same problem with below?
https://github.com/brendan-w/python-OBD/issues/111

Should I don't use 3.7 python?

**Comment by OrangeFlare** [comment]
Yes, this is the same issue you may want to close this one

**Comment by alistair23** [comment]
Closing this issue as it's a duplicate of #111
