### ISSUE TITLE
'UNABLE TO CONNECT' not catched when first querying protocol 0100

### ISSUE THREAD

**Issue by Ircama** [brendan-w/python-OBD#124]
I am not totally sure that the missing control of the return code in the [first command, SEARCH protocols](https://github.com/brendan-w/python-OBD/blob/master/obd/elm327.py#L222) ([auto protocol detection trigger](https://github.com/brendan-w/python-OBD/issues/62#issuecomment-259881967)) is an error.

The 'UNABLE TO CONNECT' message can relate to an unconnected adapter or to a connected one with engine switched off. From the manual:

*UNABLE TO CONNECT
If you see this message, it means that the ELM327 has tried all of the available protocols, and could not
detect a compatible one. This could be because your vehicle uses an unsupported protocol, or could be as simple as forgetting to turn the ignition key on. If you are sure that your vehicle uses an OBDII protocol, then check all of your connections, and the ignition, then try the command again.*

As the OBD-II spec guarantees that [protocol '0100' is supported by all cars](https://github.com/brendan-w/python-OBD/issues/62#issuecomment-259881967), an error here should mean that the ignition is off. But with my adapter this error also occurs when it is disconnected from the car. I am unsure that this is appropriate because unfortunately all my adapters return "ELM327 v1.5", so not the original ELM327 firmware; perhaps the original firmware wants this preliminary unchecked query.

Also, the [OBDStatus.CAR_CONNECTED](https://github.com/brendan-w/python-OBD/blob/master/obd/utils.py#L49) does not clarify whether the ignition shall also be on, but, as there is no differentiation (provided that this can be done in some way), it looks like CAR_CONNECTED means adapter connected and ignition on.

Anyway, after adding [this control in my branch](https://github.com/Ircama/python-OBD/commit/31a035cef26a19799161b4e8c84d5b8d1632b49d), the CAR_CONNECTED status only returns when the adapter is connected and the ignition is on (`status()` returns 'Car Connected'). Otherwise `status()` returns 'ELM Connected'.

If you think that this is correct, I'll perform a pull request.

**Comment by alistair23** [comment]
I'm not clear on what you mean here. I think it would be best if you do create a pull request and we can discuss it there.
