### ISSUE TITLE
import obd very slow

### ISSUE THREAD

**Issue by kayjayme** [brendan-w/python-OBD#136]
On my raspberry pi 'import obd' takes more than 10 seconds to complete. Is there and way to speed this up ?

**Comment by alistair23** [comment]
Have you looked at the logs of what it is doing?

It's probably slow figuring out the baud rate, you can hard code that to save time.

**Comment by tokfrans03** [comment]
Same here, why does it take so long to import?

**Comment by brendan-w** [comment]
yeah, I noticed this as well. Haven't profiled it, but my hunch would be the massive [DTC](https://github.com/brendan-w/python-OBD/blob/master/obd/codes.py#L33) and [command tables](https://github.com/brendan-w/python-OBD/blob/master/obd/commands.py#L51) that get instantiated upon import. Would probably be best to move these to a file that is searched/accessed at runtime.
