### ISSUE TITLE
I have some problem in using obd package.

### ISSUE THREAD

**Issue by JanghoChu** [brendan-w/python-OBD#157]
* OBD Pakage ver : v0.7.1 
* OSX, USB Serial(OBDII),  ECU Simulation Module, 
 
I had used two ECU Protocol " '5': ISO_14230_4_fast "  and  "'3': ISO_9141_2".
('portstr': '/dev/tty.usbserial')

Could you tell me how to fix it ? 

### source code 
```
    import obd

    connection = obd.OBD() # auto-connects to USB or RF port
    cmd = obd.commands.SPEED # select an OBD command (sensor)
    response = connection.query(cmd) # send the command, and parse the response
```
### log message 
```
python3 testOBD.py
[obd.elm327] Failed to retrieve current protocol
[obd.elm327] Connected to the adapter, but failed to connect to the vehicle
[obd.obd] Cannot load commands: No connection to car
[obd.obd] 'b'010D': Vehicle Speed' is not supported
```

**Comment by alistair23** [comment]
It looks like the car isn't on or the adapter isn't connected to the vehicle. Have you checked your connection?
