### ISSUE TITLE
handle length attribute for multi-frame messages

### ISSUE THREAD

**Issue by brendan-w** [brendan-w/python-OBD#16]
Currently, python-OBD does not truncate multi-frame messages based on the indicated length. This isn't an urgent problem, since python-OBD doesn't formally support any multi-frame commands (other than GET_DTC requests, but those are handled differently) I'd like the get this implemented eventually.

The infrastructure is already in place (see [protocol_can.py](https://github.com/brendanwhitfield/python-OBD/blob/master/obd/protocols/protocol_can.py), and [protocol_legacy.py](https://github.com/brendanwhitfield/python-OBD/blob/master/obd/protocols/protocol_legacy.py)). It will stitch the various frames together, and record the length marking bits, but it will not truncate the data. Some research should be done to determine exactly how this needs to be implemented.

**Comment by brendanwhitfield** [comment]
implemented CAN data length handling in commit f3aa467
