### ISSUE TITLE
PID for get unique number of vehicule 

### ISSUE THREAD

**Issue by BedoM** [brendan-w/python-OBD#165]
Hello,

I want get one codes(VIN) uniq per car, i see the "Services_09" PID 02

Can i use with the python-OBD ?

Ressources:
https://en.wikipedia.org/wiki/OBD-II_PIDs#Service_09

**Comment by alistair23** [comment]
There is a PR to add support: https://github.com/brendan-w/python-OBD/pull/151

It looks like the author stopped working on it. If you can fix up the comments it could be merged into master then you can read the VIN.

**Comment by alistair23** [comment]
Closing as a duplicate of: https://github.com/brendan-w/python-OBD/issues/42
