### ISSUE TITLE
Is Mode 01 Command 5E FUEL_RATE supported and tested?

### ISSUE THREAD

**Issue by wallem89** [brendan-w/python-OBD#176]
When using this awesome library I can read a lot of signals but if I request the fuel rate (Mode 01 Command 5E FUEL_RATE) there is no (valid) response. If I request all supported commands I get a list of around 40 supported commands for mode 01 but FUEL_RATE is not one of them.

In TorquePro I can read the fuel rate of my 2011 Ford Focus so it looks like this library is not supporting this PID (correctly)? Does anyone have an other experience?

If I look in the code in [commands.py on line 151](https://github.com/brendan-w/python-OBD/blob/master/obd/commands.py#L151) the configuration seems correct. 

I haven't tried (yet) to add the command manually as a custom command and check if it works but I suspect some issue.

**Comment by alistair23** [comment]
It's possible that the TorquePro is not using the standard `FUEL_RATE` PID and is instead using a custom PID.

I think the main thing would be to check to see what the TorquePro is doing.
