### ISSUE TITLE
A few issues & patches for initial connection & PID scan

### ISSUE THREAD

**Issue by trishmapow** [brendan-w/python-OBD#178]
I tried using this library to connect to a cheapo ELM327 Mini and ran into a few connection issues, I made a few rather ugly patches here: https://github.com/trishmapow/python-OBD/commit/ccd3e5c71032fd30717b83d5f93613ace153dbf4. 

I had to add `delay=1` to the ATH1 and AT RV commands otherwise the module doesn't seem to have enough time to respond, and an extra replace in AT RV because my module outputted the prompt char `>` instead of `v` when returning the voltage (not sure why).

The module also returns 3 elements instead of 1 for `ATDPN`, in the format `SEARCHING [bunch of hex] [version no]` so I had to take the last element. 

I also had to make the `__isok` check less strict by using `in` instead of an equality `==`. 

Finally the program seemed to keep saying no acceptable message for PIDs 01-20, turns out if I remove the `(self.ecu & m.ecu) > 0` check everything works fine. 

I didn't make a pull request because I don't know what the best way of handling this is, seems like my module is an edge case. Perhaps there could be a flag to make the checks more delayed and less strict and/or a note in the docs in case someone runs into these same issues. Hope this helps someone.

**Comment by alistair23** [comment]
I don't think we want to merge code back to support knock-off devices. If you do have a correct fix please send a PR.
