### ISSUE TITLE
Unable to use mode 9 VIN command

### ISSUE THREAD

**Issue by Leweyy** [brendan-w/python-OBD#189]
Im currently using version v0.7.1 with python version 3.8 and i am unable to use the newly implemented mode 9 commands

`$ pip freeze | grep obd`
`obd==0.7.1`

Ive tried the following tests all which return false
`OBD.commands.has_command(OBD.commands.VIN)`
`OBD.commands.has_name('VIN')`
`'VIN' in OBD.commands`
`OBD.commands.has_pid(9, 0o2)`

**Comment by alistair23** [comment]
Can you use the master branch. That is the only one with VIN support

**Comment by Leweyy** [comment]
Ive just removed obd v0.7.1 and install directly from git using `pip3 install git+https://github.com/brendan-w/python-OBD.git#egg=python-OBD` and im still facing the same issue im actually running python version 3.7.3 not 3.8x
