### ISSUE TITLE
Decode DTCs

### ISSUE THREAD

**Issue by brendan-w** [brendan-w/python-OBD#2]
I'd like to cleanup the old pyobd DTC decoders, and see if the bit-shifting madness can be quelled. There are untested decoders for DTCs in decoders.py. These need to be tested on a car that throws a code (something I don't have at the moment (oh darn...)). For reference, the old pyobd decoder is still in port.py (commented out).

**Comment by ryanbagwell** [comment]
@brendanwhitfield I might be able to help, as I have a car that currently has 4 DTCs. How do I query for the actual DTC codes?

**Comment by brendanwhitfield** [comment]
I've got a branch called `dtc` going. Either `fetch` or [download](https://github.com/brendanwhitfield/python-OBD/archive/dtc.zip) it, and install `pyserial` if you don't have it already. Run this snippet from the repo root to take it for a test drive:

```python
import obd
obd.debug.console = True

o = obd.OBD()
print(o.query_DTC())
```

Please send me the debug output (the last line *should* be a list of error codes). There's a lot of development code in here, so if it crashes and burns, the debug should tell me everything I need to know.

Let me know how it goes!

**Comment by ryanbagwell** [comment]
Darn, I wish I had seen the dtc branch before I spent a few hours getting this to work. I will run it again tomorrow. I see you made a lot of improvements.

This is a great refactor. Thanks for doing it.

**Comment by ryanbagwell** [comment]
````
>>> conn.query_DTC()
[obd] Sending command: 0101: Status since DTCs cleared
[obd] write: '0101\r\n'
[obd] read: '48 6B 10 41 01 84 07 6D 00 FD \r\r'
[obd] Sending command: 03: Get DTCs
[obd] write: '03\r\n'
[obd] read: '48 6B 10 43 03 00 03 02 03 03 14 \r48 6B 10 43 03 04 00 00 00 00 0D \r\r'
[obd] Recieved multi-frame response. Can't parse those yet
[obd] Failed to retrieve DTCs
````

I do have two DTCs that are currently being thrown.

**Comment by brendanwhitfield** [comment]
Yeah, I was afraid of that. Protocol abstraction system isn't 100% yet. Now that I have the raw tx/rx data though, I can do more tests over here. I haven't gotten around to making obdsim put out more than 3 DTCs.

Thank you! This helps a lot

**Comment by brendanwhitfield** [comment]
Alright, master (856b5de96e) should be good to go. I tried it on your debug output and it parsed just fine.

**Comment by brendan-w** [comment]
This decoder now handles multiple DTC messages from all ECU's. Slated for 0.5.0 release.
