### ISSUE TITLE
New Connections: J2534 Cable

### ISSUE THREAD

**Issue by MasterCodeIT** [brendan-w/python-OBD#223]
I have the J2534 working well and I want to integrate pyobd with it but I need to "add" this as new connections.

Ideas?

**Comment by csurf** [comment]
python-OBD is designed to work specifically with the ELM327 family of devices. J2534 is a completely different communication standard that relies on having combination of J2534 hardware & drivers, as well as vehicle manufacturer-specific software that knows how to communicate with the target vehicle over the J2534 link. So, it's basically an 'apples and oranges' situations. Python-OBD simply isn't designed and cannot be modified to work with J2534.
