### ISSUE TITLE
ATH1 did not return 'OK', or echoing is still ON ELM327.py

### ISSUE THREAD

**Issue by Diegofdez1** [brendan-w/python-OBD#227]
I was getting the following error:

![elm327-bug](https://user-images.githubusercontent.com/12657987/133770298-de28e827-3c33-41d8-9826-1854b17810bd.png)

And I have solved it by adding delays in the following lines of elm327.py:

157:  r = self.__send(b"ATE0", delay=1)
163:  r = self.__send(b"ATH1", delay=1)
169:  r = self.__send(b"ATL0", delay=1)

**Comment by ddowling** [comment]
I think this is the same issue that I reported in https://github.com/brendan-w/python-OBD/issues/226.
If you want try my fix and let me know how it goes.
