### ISSUE TITLE
Incompatible with python 3.10 due to collections.MutableMapping deprecation

### ISSUE THREAD

**Issue by j-schmied** [brendan-w/python-OBD#229]
Behaviour is reproducable on Windows 10/11, MacOS 11.6, Kali Linux 2021.3 and was already announced when importing MutableMapping on Python<=3.9

ImportError: cannot import name 'MutableMapping' from 'collections' (C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py)

Solution: using collections.abc.MutableMapping should fix the issue (source: https://docs.python.org/3/library/collections.abc.html)

**Comment by jakka351** [comment]
I got this error, was able to get library working by uninstalling all instances of one via `pip uninstall obd` and then re installing via `pip install +git https://GitHub.com/brendan-w/python-obd@master`
