### ISSUE TITLE
Which python version to work with?

### ISSUE THREAD

**Issue by yuxiaolejs** [brendan-w/python-OBD#245]
My computer is running python 3.10.4, but getting import error: cannot import name 'Chainmap' from 'collections' when trying to start the program, which version should I use instead?

**Comment by pcakhilnadh** [comment]
Issue fix 
#c7be924a21c5d0be87cce51e3087e8fb21a0ecf2

Now supports Py 3.10.x

**Comment by jakka351** [comment]
Just having this same issue now
