### ISSUE TITLE
Clear specific Code

### ISSUE THREAD

**Issue by Peskedor** [brendan-w/python-OBD#253]
I saw you can clear all codes or specify an ECU, but is it possible to only clear a certain code and leave all others? As far as I can tell, there is no option/support in this library for that - but I'm not even sure if that's a possibility over the OBD protocol in general?

**Comment by csurf** [comment]
not possible w/ OBD2 protocol. That's not how the protocol works.
see here:
https://en.wikipedia.org/wiki/OBD-II_PIDs#Service_04
