### ISSUE TITLE
Using bluetooth on MAC

### ISSUE THREAD

**Issue by boazin** [brendan-w/python-OBD#29]
Question: How can I use python-OBD on Mac OS?

In the wiki it says:
`sudo apt-get install bluetooth bluez-utils blueman`

What are the MAC equivalent?

**Comment by brendanwhitfield** [comment]
Your Mac already has Bluetooth facilities builtin, so you should be able to pair with the adapter using the Mac's UI. I believe you can set it up as a standard RS-232 device (if it isn't already). It should show up as /dev/tty.*, which python-OBD should automatically detect.
