### ISSUE TITLE
Developing a simple logger

### ISSUE THREAD

**Issue by rshigemura** [brendan-w/python-OBD#35]
Hi!

I'd been wondering how to develop a simple data logger (RPM, KPH) based on python-OBD functions.

How could I do ? Some Idea ?

Thanks in Advance!

**Comment by brendan-w** [comment]
I wrote some basic logging examples a little while ago, I just haven't gotten around to pushing them to master. Let me know if you run into any problems.

https://github.com/brendan-w/python-OBD/blob/examples/docs/Examples.md

**Comment by rshigemura** [comment]
Wow! Awesome!

Worked fine for me!

Thanks!
