### ISSUE TITLE
Error - "Failed to choose primary ECU"

### ISSUE THREAD

**Issue by bendrick92** [brendan-w/python-OBD#38]
After utilizing 'bluetoothctl' to pair and 'rfcomm bind 0' to bind my bluetooth OBD adapter to '/dev/rfcomm0', I get the following error when attempting to initialize an OBD connection:

```
Connection Error
Failed to choose primary ECU
```

I've followed the steps outlined in the documentation with no luck.  I'm running Raspbian Jessie Lite, which seems to utilize a different pairing process than typical, but I don't believe that's causing the issue.

Here's the error output from the debug log:

```
[obd] write: '0100\r\n'
[obd] __read() found nothing
[obd] read: 'SEARCHING...\rUNABLE TO CONNECT\r\r'
[obd] write: 'ATDPN\r\n'
[obd] read: 'A8\r\r'
[obd] Connection Error:
[obd]      Failed to choose primary ECU
[obd] Failed to connect
```

**Comment by brendan-w** [comment]
The computer successfully connected to your adapter, but the adapter couldn't connect to the car. When this happens to me, it's usually a hardware problem, like a flaky OBD-II connector, or forgotting to turn on the car.

Hope this helps, sorry about the not-so-helpful debug output

**Comment by bendrick92** [comment]
Thanks for the quick reply!  I will try a different OBD-II adapter tonight and report back.  Some additional research has got me thinking it might be Bluetooth permissions in the new release of Raspbian.

**Comment by brendan-w** [comment]
Doesn't look like a bluetooth problem. That line that says `SEARCHING...\rUNABLE TO CONNECT\r\r` is actually your adapter talking back to your computer, so it looks like the bluetooth is working perfectly. That message is only given when the adapter's OBD side can't find the car.

**Comment by brendan-w** [comment]
Still having issues?

**Comment by bendrick92** [comment]
Thanks for checking back!  I forgot about this.  Haven't seen the issue pop up in a few months now, so I'll consider it resolved!
