### ISSUE TITLE
VIN Support

### ISSUE THREAD

**Issue by fewhnhouse** [brendan-w/python-OBD#42]
Are there plans to add VIN Support to python-OBD (Code 0902)?
[https://en.wikipedia.org/wiki/OBD-II_PIDs#Mode_09](url)

**Comment by brendan-w** [comment]
I saw you, don't worry. Will be working on this soon. Hasn't been at the top of my list, since none of my vehicles support this PID (they're old). Thus, I can't really test it, outside of examples in the standards docs. Once I get something implemented, I'll encourage people to test it out.

**Comment by Fr3ak1n0ut** [comment]
Alright, thanks ;) 
I already implemented this on my own, might submit a pull request soon :)

**Comment by brendan-w** [comment]
Sweet, please do!

**Comment by kellogsgit** [comment]
I will work on this feature. I would also like to extract brand from VIN in order to be able to derive a new class for each brand.

**Comment by brendan-w** [comment]
https://github.com/brendan-w/python-OBD/blob/master/obd/commands.py#L292

Have at it. Never been tested.

**Comment by farshadz** [comment]
Dear Brendan:
I tested your code for VIN, unfortunately it is not working for my case and recieveing Get Vehicle information is not supported. After I search,I guess because my car using CAN bus (BMW Serie 1) and it return the data in multiple messages. I have not go through your code yet to find a solution. Just wanted to let you know about the test.

**Comment by pmundt** [comment]
As there doesn't appear to have been any progress on this front, I assume the current status is still unchanged, and that the Mode 9 commands that were added and later removed from commands.py are where things were left off.

We have an OBD-II simulator that can utilize most of the available protocols, and are happy to test this out. As we would like to support VIN-retrieval via Mode 9 in our app, we'll have a go at extending what's already there and extending it for a couple of different protocols.

**Comment by alistair23** [comment]
It doesn't look like anyone has worked on this.

That would be great if you could add support. I will be happy to review your pull requests and help get your work merged.
