### ISSUE TITLE
Autodetect baudrate

### ISSUE THREAD

**Issue by Mark-Hetherington** [brendan-w/python-OBD#44]
Currently calling:
connection = obd.OBD()
Errors on my device, with some kind of decoding error. Setting the baudrate allows a connection. However I believe it should be possible to autodetect the baudrate, by cycling through the possible baudrates.

I hope to implement this and create a pull request in the near future.

**Comment by Mark-Hetherington** [comment]
Close as duplicate of #26.

**Comment by brendan-w** [comment]
Yup, got it, thanks though! There's an ELM command for testing baudrate divisors, so I'll be using that.

**Comment by Mark-Hetherington** [comment]
If I'm not mistaken a connection at the correct baud rate would have to already be established to issue that command though? I suppose once connected, switching to the fastest available baud rate would be nice.

**Comment by brendan-w** [comment]
I added some notes and a reference implementation to the original issue
