### ISSUE TITLE
Can not connect (freezing during connection)

### ISSUE THREAD

**Issue by gqchen1** [brendan-w/python-OBD#77]
I bought a Sannysis V1.5Mini ELM327 (bluetooth) OBD scanner from amazon, it works great when I use my android phone to connect it with my Nissan leaf (via leafspy app).  When I tried to connect it in my Windows 10 laptop with python-obd, it always freeze during connection stage ( port is correct 'COM3') as shown in the log message.  Any advice on how to proceed? Thanks

**Comment by kellogsgit** [comment]
Have a look at this patch:
https://github.com/brendan-w/python-OBD/pull/84

It may help you debug your connection in order to find the correct setting.
