### ISSUE TITLE
Command ATMA (Monitor All Messages)

### ISSUE THREAD

**Issue by leard** [brendan-w/python-OBD#78]
Hi,
Is it possible monitor all messages with this library (AT MA, from elm327 datasheet) ? I want all raw data.

**Comment by brendan-w** [comment]
Not with this library (yet). I've also heard that doing it with the  ELM327's can be a challenge because the buffers fill up quickly if your MID mask is too wide, but your mileage may vary. If you want everything (including raw control), then I'd suggest going for a genuine CAN dongle.

**Comment by kellogsgit** [comment]
I will have a try on my fork to study how ATMA works. All is described in the documentation. My car, a Renault Espace IV, sends mostly messages on CAN.

**Comment by nirlandau** [comment]
is this feature available yet?
